### ISSUE TITLE
can't redirect where client from after login or signup  

### ISSUE THREAD

**Issue by kamruzzaman-dev** [mohammad-shariar-parvez/sunrise-eye-care#1]
actually you get location where your user from but you not assign navigate to the from directory.

**Comment by kamruzzaman-dev** [comment]
import {useNavigate } from 'react-router-dom';
const navigate = useNavigate();

if (user) {
        navigate(from, { replace: true });
 }

**Comment by kamruzzaman-dev** [comment]
add those line code problem will be solve

**Comment by mohammad-shariar-parvez** [comment]
Thank you for your cooperation
